name: Rules check

on:
  pull_request:
    paths:
      - '**/*' 

jobs:
  check-newline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch --all

      - name: List scripts directory
        run: ls -l .github/workflows/scripts/

      - name: Debug SHA and branch
        run: |
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          git log --oneline --decorate --graph -20
          git branch -a

      - name: Check for newline at end of files
        run: python .github/workflows/scripts/newline.py
