name: Rules check

on:
  pull_request:
    paths:
      - '**/*' 

jobs:
  check-newline:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for newline at end of files
        run: python .github/workflows/scripts/newline.py
      
      - name: Run clang-format style check for 
        uses: jidicula/clang-format-action@v4.16.0
        with:
          clang-format-version: '13'
          check-path: '.'
          fallback-style: 'Google'
